apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  namespace: demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: __acrName__.azurecr.io/simpleapp:__imageTag__
        imagePullPolicy: Always
        name: simpleapp
